### ISSUE TITLE
Could you please upload a LICENSE?

### ISSUE THREAD

**Issue by Benjamin-Dobell** [fsharpco/mongoose-snake-to-camel#1]
First, thanks for the package, very much appreciated 😄 

I'm performing a license audit and this package was signalled as one without a license. You mentioned forking from `mongoose-convention` which is [MIT licensed](https://github.com/vatson/mongoose-convention/blob/master/LICENSE), so I suspect your intention is that this is also MIT license.

Nonetheless, if you could please upload a `LICENSE` file to GIthub and/or add the license to [package.json](https://docs.npmjs.com/files/package.json#license) that'd very much appreciated.

**Comment by tmont** [comment]
Added MIT license and published to NPM at `mongoose-snake-to-camel@0.3.0`
